[package]
name = "virtualbutfake/tailwind"
description = "Tailwind colors in Luau"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "dist",
    "dist/**",
    "LICENSE.md",
    "wally.toml",
    "default.project.json"
]
exclude = ["*", "build.rbxm"]
[dependencies]