[package]
name = "shebov3/roblox"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
maid = "kroogate/maid@0.4.3"

lemonSignal = "data-oriented-house/lemonsignal@1.10.0"
spark = "nezuo/spark@0.2.1"
spring = "mastrickdev/spring@0.2.4"
rewire = "sayhisam1/rewire@0.3.0"
smartbone-2 = "jakeywastaken/smartbone-2@0.3.1"

# UI
iris = "michael-48/iris@2.2.0"
neohotbar = "imavafe/neohotbar@1.1.1"
fusion = "acecateer/fusion@0.3.1"
lydie = "7kayoh/lydie@0.1.0"

# RedBlox Util
Bin = "red-blox/bin@^1.0.0"
Clock = "red-blox/clock@^1.0.0"
Collection = "red-blox/collection@^1.0.0"
Fetch = "red-blox/fetch@^2.0.0"
Future = "red-blox/future@^1.0.0"
Guard = "red-blox/guard@^1.0.0"
Promise = "red-blox/promise@^1.0.0"
Ratelimit = "red-blox/ratelimit@^1.0.0"
Signal = "red-blox/signal@^2.0.0"
Spawn = "red-blox/spawn@^1.0.0"