[package]
name = "shebov3/roblox"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
fusion = "acecateer/fusion@0.3.1"
lemonSignal = "data-oriented-house/lemonsignal@1.10.0"
iris = "michael-48/iris@2.2.0"
spring = "mastrickdev/spring@0.2.4"
