[package]
name = "shebov3/roblox"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusionComponents = "virtualbutfake/fusion-components@0.1.16"
themeFramework = "virtualbutfake/theme-framework@0.1.6"
fusionUtils = "virtualbutfake/fusion-utils@0.1.2"
tailwind = "virtualbutfake/tailwind@0.1.1"

boattween = "boatbomber/boattween@1.0.1"
warp = "imezx/warp@1.0.12"
spring = "mastrickdev/spring@0.2.4"
smartbone-2 = "jakeywastaken/smartbone-2@0.3.1"
iris = "michael-48/iris@2.2.0"
neohotbar = "imavafe/neohotbar@1.1.1"
Fusion = "elttob/fusion@0.2.0"
Lydie = "7kayoh/lydie@0.1.0"
Bin = "red-blox/bin@^1.0.0"
Clock = "red-blox/clock@^1.0.0" 
Collection = "red-blox/collection@^1.0.0"
Future = "red-blox/future@^1.0.0"
Ratelimit = "red-blox/ratelimit@^1.0.0"
Signal = "red-blox/signal@^2.0.0"
Spawn = "red-blox/spawn@^1.0.0"
# promise = "evaera/promise@4.0.0"
# maid = "kroogate/maid@0.4.3"
# spark = "nezuo/spark@0.2.1"
# rewire = "sayhisam1/rewire@0.3.0"
# Fetch = "red-blox/fetch@^2.0.0"