[package]
name = "shebov3/roblox"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
maid = "kroogate/maid@0.4.3"
lemonSignal = "data-oriented-house/lemonsignal@1.10.0"
spark = "nezuo/spark@0.2.1"
iris = "michael-48/iris@2.2.0"
spring = "mastrickdev/spring@0.2.4"
matter = "matter-ecs/matter@0.8.1"
rewire = "sayhisam1/rewire@0.3.0"
neohotbar = "imavafe/neohotbar@1.1.1"
fusion = "acecateer/fusion@0.3.1"
lydie = "7kayoh/lydie@0.1.0"
smartbone-2 = "jakeywastaken/smartbone-2@0.3.1"
cmdr = "evaera/cmdr@1.12.0"