[package]
name = "mastrickdev/spring"
version = "0.2.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Springs are powerful approach for describing fluid, physically-based animation. Spring is a high-performance and user-friendly motion library for Roblox based on springs."

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"