[package]
name = "imavafe/neohotbar"
description = "A modern, flexible hotbar for Roblox"
version = "1.1.1"
license = "MIT"
authors = ["Avafe"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Fusion = "elttob/fusion@0.2.0"
FusionUtils = "hexcede/fusion-utils@0.1.2"
