[package]
name = "acecateer/fusion"
description = "A forked version of fusion"
license = "MIT"
authors = ["Elttob"]
version = "0.3.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
