[package]
name = "virtualbutfake/theme-framework"
description = "A straightforward theme framework, designed for use with Fusion 0.2"
version = "0.1.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "dist",
    "dist/**",
    "LICENSE.md",
    "wally.toml",
    "default.project.json",
]
exclude = ["*", "build.rbxl"]
[dependencies]
fusion = "elttob/fusion@0.2.0"
fusionUtils = "virtualbutfake/fusion-utils@0.1.2"
tailwind = "virtualbutfake/tailwind@0.1.1"
