name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup-aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - run: rojo build -o game.rbxl

      - run: rbxcloud experience publish -f game.rbxl -p 16147099744 -u 5578645345 -t published -a ${{ secrets.API_KEY}}