name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      steps:
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v1.0.0 # name of git tag in aftman (uses latest tag by default)
          path: . # path to project dir containing `aftman.toml` ("." (current dir) by default)
          cache: false # whether to enable binary caching between runs (false by default)
          token: ${{ github.token }} # GitHub token to bypass rate limit (${{ github.token }} set by default)


      - name: Lint
        run: |
          selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install StyLua
        run: |
          curl -sSL https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux.zip -o stylua.zip
          unzip stylua.zip -d /usr/local/bin
          rm stylua.zip

      - name: Run StyLua
        run: |
          stylua ./src
