name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Aftman
        run: |
          curl -sSL https://github.com/LPGhatguy/aftman/releases/download/v0.5.3/aftman-linux-x86_64.zip -o aftman.zip
          unzip aftman.zip -d aftman
          sudo mv aftman/aftman /usr/local/bin/aftman
          rm -rf aftman.zip aftman
          aftman init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install StyLua
        run: |
          curl -sSL https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux.zip -o stylua.zip
          unzip stylua.zip -d /usr/local/bin
          rm stylua.zip

      - name: Run StyLua
        run: |
          stylua ./src
